# 5.16 List Dua Dimensi
####            List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matriks, yaitu terdapat indeks kolo dan baris.

In [1]:
nim = [
    [1,2,3,4,5],
    [5,6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
]
print(nim)
#list ini terdiri dari 4 baris dan masing-masing terdiri dari 4  kolom (dihitung mulai dari 0)

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]


In [2]:
nim [0]
#variabel nim dengan indeks baris ke-0

[1, 2, 3, 4, 5]

In [3]:
nim [1]
#variabel nim dengan indeks baris ke-1

[5, 6, 7, 8, 9, 10]

In [4]:
nim [0][0]
# variabel nim dengan indeks baris ke-0 dan kolom ke-0

1

In [5]:
nim [4][4]
# variabel nim dengan indeks baris ke-4 dan kolom ke-4

25

In [6]:
nim [2][3]
# variabel nim dengan indeks baris ke-2 dan kolom ke-3

14

In [7]:
nim[4][4]=26
print(nim[4][4])
#merubah isi list pada indeks baris ke-4 dan kolom ke-4

26


In [8]:
nim
#menampilkan isi list yang baru

[[1, 2, 3, 4, 5],
 [5, 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 26]]

In [9]:
for baris in nim:
    print(baris)
    for kolom in baris:
        print (kolom)
#untuk menampilkan list dan anggotanya dapat juga menggunakan dengan perintah for

[1, 2, 3, 4, 5]
1
2
3
4
5
[5, 6, 7, 8, 9, 10]
5
6
7
8
9
10
[11, 12, 13, 14, 15]
11
12
13
14
15
[16, 17, 18, 19, 20]
16
17
18
19
20
[21, 22, 23, 24, 26]
21
22
23
24
26


In [10]:
for baris in nim:
    print(baris)
for kolom in baris:
        print (kolom)
#perlu diperhatikan cara penulisan for. Bandingkan kode ini dengan kode sebelumnya.
#

[1, 2, 3, 4, 5]
[5, 6, 7, 8, 9, 10]
[11, 12, 13, 14, 15]
[16, 17, 18, 19, 20]
[21, 22, 23, 24, 26]
21
22
23
24
26


# 5.17 Tuples
#### Tuples tidak jauh berbeda dengan list, perbedaannya adalah pada tuples isinya tidak dapat dirubah, sedangkan list bisa. Penulisannya juga menggunakan kurung biasa. Untuk mengakses nilai tuples, gunakan indeks seperti pada list.

In [11]:
brand = (69, 'gucci', 'hm', 'colorbox', 'uniqlo')
#anggotanya dapat berupa angka maupun string, demikian juga pada list

In [12]:
print(brand[0])

69


In [13]:
print(brand[0:3])

(69, 'gucci', 'hm')


In [14]:
print (brand[1:3])

('gucci', 'hm')


In [15]:
print (brand[1:2])

('gucci',)


In [16]:
for isi in brand[0:4]:
    print(isi)

69
gucci
hm
colorbox


In [17]:
brand[1]= 'chanel'
#mecoba untuk mengganti isi dari tuples

TypeError: 'tuple' object does not support item assignment

In [18]:
brand.append('zara')
#append digunakan untuk menambahkan anggota, maka hal ini tidak berlaku pada tuples

AttributeError: 'tuple' object has no attribute 'append'

In [19]:
brand.remove(69)
#remove digunakan untuk menghilangkan atau menghapus anggota, 
#pada tuples selain tidak dapat menambahkan, juga tidak dapat mengurangi karena tuples tidak dapat diubah anggotanya

AttributeError: 'tuple' object has no attribute 'remove'

In [20]:
brand.count(69)
#menghitung berapa ada nilai yang akan dicari, pada kode ini kita menghitung berapa ada merk 69

1

In [21]:
brand.index('hm')
#digunakan untuk melihat anggota dari tuples berada pada indeks keberapa, 
#pada kode ini kita ingin mencari tau hm berada pada indeks keberapa

2

# 5.18 Dictionaries
#### Dictionaries memiliki perbedaan dengan list dan tuples. Pada dictionaries setiap urutanya berisi key dan value. Setiap key dipisahkan dari value-nya oleh titik dua (:), item dipisahkan oleh koma.  Key merupakan nama atribut suatu item pada dictionary, sedangkan value adalah nilai yang disimpan pada suatu atribut.

In [22]:
data_pendonor_darah_mhs_mat={
    'nama' : 'Anya Tentria',
    'usia' : 19,
    'golongan_darah' : 'O',
    'berat_badan' : 50,
    'memiliki_riwayat_covid_19' : False
}
# Terdiri dari 5 buah “key” atau “atribut”, yaitu:
#nama
#usia
#golongan darah
#berat badan
#memiliki riwayat covid 19
#Yang mana masing-masing atribut tersebut memiliki informasi/nilai sendiri-sendiri sesuai dengan namanya.

In [23]:
print(data_pendonor_darah_mhs_mat['nama'])

Anya Tentria


In [24]:
print(data_pendonor_darah_mhs_mat['golongan_darah'])

O


In [25]:
print(data_pendonor_darah_mhs_mat.get('nama'))
#get digunakan jika kita ingin mendapatkan salah satu informasi atau nilai dari setiap elemen yang terdapat pada dictionaries.

Anya Tentria


In [26]:
print(data_pendonor_darah_mhs_mat.get('Nama'))
#jika kode tidak dapat menemukan atau terjadi suatu kesalahan dalam penulisan kode 
#(pada contoh di atas kesalahan terletak pada variabel)
#maka output yang dihasilkan adalah None

None


In [27]:
print(data_pendonor_darah_mhs_mat.get('tanggal_lahir'))
#karena pada dictionaries tidak terdapat tanggaln lahir maka output yang muncul adalah None

None


In [28]:
print(data_pendonor_darah_mhs_mat.get('tanggal_lahir', '2-2-2010'))

2-2-2010


In [29]:
print(data_pendonor_darah_mhs_mat.get('tanggal_lahir'))

None


In [30]:
print(data_pendonor_darah_mhs_mat)

{'nama': 'Anya Tentria', 'usia': 19, 'golongan_darah': 'O', 'berat_badan': 50, 'memiliki_riwayat_covid_19': False}


In [31]:
print(data_pendonor_darah_mhs_mat['tanggal_lahir'])

KeyError: 'tanggal_lahir'

In [34]:
#jika ingin menambahkan key dan value pada dictionaries maka kita harus menginisialisasi terlebih dahulu, 
#seperti contoh berikut.

In [35]:
data_pendonor_darah_mhs_mat['tanggal_lahir']='14/11/2003'

In [36]:
data_pendonor_darah_mhs_mat['HP']='081987654321'

In [37]:
print(data_pendonor_darah_mhs_mat['HP'])

081987654321


In [38]:
print(data_pendonor_darah_mhs_mat)

{'nama': 'Anya Tentria', 'usia': 19, 'golongan_darah': 'O', 'berat_badan': 50, 'memiliki_riwayat_covid_19': False, 'tanggal_lahir': '14/11/2003', 'HP': '081987654321'}


# 5.19 Fungsi dalam Python
#### Pada dasarnya fungsi diciptakan untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi atau sering pada program yang kita buat. Jadi untuk mempermudah dan meringkas program, dibutuhkan suatu fungsi, sehingga kita dapat langsung memanggilnya jika diperlukan

In [39]:
def greeting():
    print ('Good Morning!')
#Fungsi di atas (def), jika dipanggil akan mengeksekusi perintah print() yang ada di dalamnya

In [40]:
greeting()
#jika ingin memanggil fungsi, cukup ketik nama fungsinya

Good Morning!


In [41]:
def full_name(first_name,last_name):
    print(f'Nama lengkap Anda adalah {first_name} {last_name}')
#penulisannya sedikit berbeda dengan kode sebelumnya, karena setelah nama fungsi 'full_name'
#berisi parameter '(first_name,last_name)'

In [42]:
first_name = input('Masukkan nama depan Anda : ')
last_name = input('Masukkan nama belakang Anda : ')
full_name(first_name,last_name) #yang dieksekusi adalah perintah printnya

Masukkan nama depan Anda : anya
Masukkan nama belakang Anda : pratiwi
Nama lengkap Anda adalah anya pratiwi


# 5.19.1 Tugas Fungsi pada Python
#### Ada dua jenis tugas fungsi pada Python yaitu: 
#### ˆ Menjalankan perintah.
#### ˆ Menampilkan hasil perhitungan

In [43]:
def waktu_sampai(jarak,kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [44]:
def waktu_tempuh(jarak,kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [45]:
waktu_sampai(80,60)
# tugas fungsi menjalankan perintah sekaligus menampilkan hasil perhitungan

1.3333333333333333


In [46]:
waktu_tempuh(80,60)

1.3333333333333333

In [47]:
a = waktu_sampai(80,60)
print(a)

1.3333333333333333
None


In [48]:
b = waktu_tempuh(80,60)
print(b)

1.3333333333333333


In [49]:
def peluang_A(jumlah_data,banyak_data):
    peluang = jumlah_data/banyak_data
    print (peluang)

In [50]:
def peluang_B(jumlah_data,banyak_data):
    peluang = jumlah_data/banyak_data
    print (peluang)

In [51]:
peluang_A (3,3)

1.0


In [52]:
peluang_B (24,6)

4.0


In [53]:
import numpy as np
def luas_segitiga(alas,tinggi):
    luas =(1/2)*alas*tinggi
    return luas
def luas_lingkaran(jari_jari) : 
    luas = np.pi*(jari-jari**2)
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas
#return artinya keluar dan mengembalikan nilai terkait sesegera mungkin. 
#Karena sudah ada nilai yang dikembalikan, maka eksekusi fungsi dinyatakan selesai, sehingga seluruh kode selanjutnya tidak akan dieksekusi.


In [54]:
jenis_bidang = input('Tulis jenis bidangnya : ')
if jenis_bidang == 'segitiga':
    alas = float (input('Alas : '))
    tinggi = float (input('Tinggi : '))
    luas = luas_segitiga(alas,tinggi)
    print(f'Luas {jenis_bidang} adalah {luas}')
elif jenis_bidang == 'lingkaran':
    jari_jari = float (input('Jari-Jari : '))
    luas = luas_lingakran(jari_jari)
    print(f'Luas {jenis_bidang} adalah {luas}')
elif jenis_bidang == 'persegi':
    sisi = float (input('Sisi : '))
    luas = luas_persegi(sisi)
elif jenis_bidang == 'persegi panjang':
    panjang = float (input('Panjang : '))
    lebar = float (input('Lebar : '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f'Luas {jenis_bidang} adalah {luas}')
else :
    print(f'Maaf bidang {jenis_bidang} yang anda masukkan salah.')
    print('Hanya ada pilihan segitiga, lingkaran, persegi dan persegi panjang')
    print('Mohon periksa kembali input anda')

Tulis jenis bidangnya : segitiga
Alas : 12
Tinggi : 3
Luas segitiga adalah 18.0


In [55]:
jenis_bidang = input('Tulis jenis bidangnya : ')
if jenis_bidang == 'segitiga':
    alas = float (input('Alas : '))
    tinggi = float (input('Tinggi : '))
    luas = luas_segitiga(alas,tinggi)
    print(f'Luas {jenis_bidang} adalah {luas}')
elif jenis_bidang == 'lingkaran':
    jari_jari = float (input('Jari-Jari : '))
    luas = luas_lingakran(jari_jari)
    print(f'Luas {jenis_bidang} adalah {luas}')
elif jenis_bidang == 'persegi':
    sisi = float (input('Sisi : '))
    luas = luas_persegi(sisi)
elif jenis_bidang == 'persegi panjang':
    panjang = float (input('Panjang : '))
    lebar = float (input('Lebar : '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f'Luas {jenis_bidang} adalah {luas}')
else :
    print(f'Mohon periksa kembali input anda, bidang {jenis_bidang} yang anda masukkan salah.')
    print('Hanya ada pilihan segitiga, lingkaran, persegi dan persegi panjang')


Tulis jenis bidangnya : trapesium
Mohon periksa kembali input anda, bidang trapesium yang anda masukkan salah.
Hanya ada pilihan segitiga, lingkaran, persegi dan persegi panjang


# 5.20 Numpy
#### Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi.

In [56]:
# Hal yang harus dilakukan untuk memanggil library Numpy, yaitu sebagai berikut.

In [57]:
import pandas as pd
#pandas adalah salah satu library seperti numpy

In [58]:
import numpy as np

# 5.20.1 Perintah Dasar pada Numpy

In [59]:
import numpy as np

In [60]:
j = np.array ([0,1,2,3,4,5])
print(j)
#membuat numpy format kodenya adalah np.array

[0 1 2 3 4 5]


In [61]:
k = np.array([[5,6,7,8,9],[9,8,7,6,5]])
print(k)

[[5 6 7 8 9]
 [9 8 7 6 5]]


In [62]:
l = np.array([[[0,1,2,3],[4,5,6,7]],[[8,9,10,11],[1,2,3,4]],
              [[4,3,2,1],[5,6,7,8]]])
print(l)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 1  2  3  4]]

 [[ 4  3  2  1]
  [ 5  6  7  8]]]


In [63]:
j.ndim
# ndim menyatakan jumlah dimensi 

1

In [64]:
k.ndim

2

In [65]:
l.ndim

3

In [66]:
j.shape
# Shape digunakan untuk mengetahui ordo matriks
# Terlihat bahwa ordo yang dihasilkan adalah (6, ) artinya hanya ada 6 kolom

(6,)

In [67]:
k.shape
# ordonya (2,5) artinya ada 2 baris dan  5 kolom

(2, 5)

In [68]:
l.shape
# artinya array terbagi menjadi 3 dimensi yang mana masing-masing berisi matriks 2 baris dan 4 kolom

(3, 2, 4)

# 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy
#### Memanggil anggota, kolom dan baris dalam list menggunakan Numpy dilakukan dengan contoh di bawah ini.

In [69]:
import numpy as np

In [70]:
c = np.array([[[0,1,2,3],[4,5,6,7]],[[7,6,5,4],[3,2,1,0]]])
print(c)

[[[0 1 2 3]
  [4 5 6 7]]

 [[7 6 5 4]
  [3 2 1 0]]]


In [71]:
c[0]
#numpy urutan ke-0

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [72]:
c[0,1]
#baris 0, kolom 1

array([4, 5, 6, 7])

In [73]:
c[1,:]
#baris 1 dan semua kolom

array([[7, 6, 5, 4],
       [3, 2, 1, 0]])

In [74]:
c[:,1]
#pada baris 0 posisinya dibalik, dan pada kolom 1 urutannya dibalik
#mohon maaf apabila salah, karena saya kurang paham dengan hasilnya mengapa bisa demikian.

array([[4, 5, 6, 7],
       [3, 2, 1, 0]])

# 5.20.3 Matrix pada Numpy


In [75]:
# Beberapa perintah dalam Numpy untuk membuat matriks :
#np.ones()
#np.zeros()
#np.identity()
#np.ones()
#np.full()
#np.random.rand()
#np.random.randint()

In [76]:
import numpy as np

In [77]:
#Mencoba membuat matriks berukuran 12 x 12
a=np.zeros((12,12)) 
#artinya diisi dengan angka 0 dengan ukuran 12 x 12
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [78]:
b=np.identity(12)
print(b)
#elemen identitas matriks

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [79]:
c=5*b
print(c)
#elemen identitas diganti dengan 5

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [80]:
d = np.ones((12,12)) #mengganti anggota matriks dengan angka 1
e = np.identity(12)*12 #elemen identitas 12
f = d+e #ditambahkan
print (f)

[[13.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. 13.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. 13.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1. 13.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. 13.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 13.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 13.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. 13.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. 13.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1. 13.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 13.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1. 13.]]


In [81]:
c[1:-1,1:-1] = f
print (c)
# karena matriks berukuran 12x12, maka tidak dapat diubah menjadi matriks 10x10

ValueError: could not broadcast input array from shape (12,12) into shape (10,10)

In [82]:
d = np.ones((10,10)) #mengganti anggota matriks dengan angka 1
e = np.identity(10)*10 #elemen identitas 12
f = d+e
print (f)

[[11.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. 11.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. 11.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1. 11.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1. 11.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1. 11.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1. 11.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1. 11.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1. 11.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1. 11.]]


In [83]:
c[1:-1,1:-1] = f
print (c)

[[ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 11.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 11.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1. 11.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1. 11.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1. 11.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1. 11.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1. 11.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1. 11.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1. 11.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1. 11.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]]


In [84]:
k = np.identity(6)*9
c[2:-2,2:-2]
print(c)

[[ 5.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 11.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1. 11.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1. 11.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1. 11.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1. 11.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1. 11.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1. 11.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1. 11.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1. 11.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1. 11.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  5.]]


In [85]:
h = np.ones((4,4))*3 #ordo 4x4, dengan anggota 2
i = np.identity(4)*6 #(identitasnya 7)
j = h+i #3+6=9 
print (j)

[[9. 3. 3. 3.]
 [3. 9. 3. 3.]
 [3. 3. 9. 3.]
 [3. 3. 3. 9.]]


In [86]:
c[3:-3,3:-3]=j
print (c)
# tidak dapat mengubah matriks 4x4 menjadi 6x6

ValueError: could not broadcast input array from shape (4,4) into shape (6,6)

In [87]:
k = np.identity(2)*9
c[4:-4,4:-4] = k
print (c)
#tidak dapat mengubah matriks 2x2 menjadi 4x4

ValueError: could not broadcast input array from shape (2,2) into shape (4,4)

In [88]:
j.T
# T digunakan untuk mencari transpos matriks

array([[9., 3., 3., 3.],
       [3., 9., 3., 3.],
       [3., 3., 9., 3.],
       [3., 3., 3., 9.]])

# 5.20.4 Copy pada Numpy
#### Biasanya menduplikat suatu variabel dengan maksud untuk mempercepat pekerjaan kita. Akan tetapi hubungan dari  persamaan dalam Numpy sangat erat, sehingga saat anggota variabel baru dirubah, dampaknya juga akan merubah variabel asalnya. Untuk menghindari perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah copy

In [89]:
import numpy as np

In [90]:
h= np.array([0,1,2,3,4])
print(h)

[0 1 2 3 4]


In [91]:
g=h
print (g)

[0 1 2 3 4]


In [92]:
g[4]=100
print (g)
# mengubah anggota numpy pada indeks 0

[  0   1   2   3 100]


In [93]:
print(h)
#numpy akan berubah anggotanya

[  0   1   2   3 100]


In [94]:
i= np.array([0,1,2,3,4])
print(i)

[0 1 2 3 4]


In [95]:
j=i.copy()
print(j)

[0 1 2 3 4]


In [96]:
j[4]=100
print(j)

[  0   1   2   3 100]


In [97]:
print(i)
#numpy tidak berubah, karena pada j sudah berisi perintah copy

[0 1 2 3 4]


# 5.20.5 Operasi Matematika pada Numpy
#### Beberapa operasi matematika pada Numpy yaitu sebagai berikut.

In [98]:
import numpy as np

In [99]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [100]:
y = np.array([4,3,2,1])
print(y)

[4 3 2 1]


In [101]:
x+1
#pada variabel x masing-masing anggota numpy ditambah 1

array([2, 3, 4, 5])

In [102]:
x-3
#pada variabel x masing-masing anggota numpy dikurang 3

array([-2, -1,  0,  1])

In [103]:
y*5
#pada variabel y masing-masing anggota numpy dikali 5

array([20, 15, 10,  5])

In [104]:
y/2
#pada variabel y masing-masing anggota numpy dibagi 2

array([2. , 1.5, 1. , 0.5])

In [105]:
y**2
#pada variabel y masing-masing anggota numpy dipangkatkan 2

array([16,  9,  4,  1], dtype=int32)

In [106]:
x+y
#variabel x + variabel y

array([5, 5, 5, 5])

In [107]:
x-y
#variabel x - variabel y

array([-3, -1,  1,  3])

In [108]:
x*y
#variabel x dikali variabel y

array([4, 6, 6, 4])

In [109]:
y/x
#variabel y : variabel x

array([4.        , 1.5       , 0.66666667, 0.25      ])

In [110]:
y**x
#variabel y pangkat variabel x

array([4, 9, 8, 1], dtype=int32)

# 5.20.6 Perkalian Matriks pada Numpy
#### Dapat diamati bahwa operasi matematika pada suatu matrik dengan Numpy akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua matrik. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4)

In [111]:
import numpy as np

In [112]:
k = np.array([[1,3,5,7],[2,4,6,8]])
print(k)
#matriks 2x4

[[1 3 5 7]
 [2 4 6 8]]


In [113]:
l = np.array([[2,3,5,7],[0,1,2,3]])
print(l)
#matriks 2x4

[[2 3 5 7]
 [0 1 2 3]]


In [114]:
m = k*l
print(m)
#mengalikan anggota variabel k dan l

[[ 2  9 25 49]
 [ 0  4 12 24]]


In [115]:
n = np.matmul(k,l)
#perintah matmul digunakan untuk mengalikan matriks pada numpy
#terjadi error karena pada kolom dan baris yang akan dikalikan tersebut jumlahnya berbeda

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [116]:
o = np.array([[1,2],[3,4],[5,6],[7,8]])
print (o)
#matriks 4x2

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [117]:
p = np.matmul(k,o)
print (p)
#jika matriks k dikali o dengan perintah matmul maka akan ada hasilnya, karena sudah memenuhi aturan perkalian matriks

[[ 84 100]
 [100 120]]


# 5.20.7 Min, Max dan Sum pada Numpy
#### Perintah min, max dan sum cukup sering digunakan untuk mengetahui nilai minimum, maksimum dan penjumlahan.

In [118]:
import numpy as np

In [119]:
k = np.array ([[5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
print(k)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [120]:
l = np.min(k)
print(l)
#menampilkan nilai minimmum dari matriks k

5


In [121]:
m = np.min(k,axis=0)
#axis=0 digunakan untuk menerapkan metode di setiap kolom, atau ke label baris (indeks), 
#disertai perintah min artinya baris yang paling kecil
print(m)

[5 6 7 8]


In [122]:
n =np.min(k,axis=1)
print(n)
#axis=1 digunakan untuk menerapkan metode di setiap baris, atau ke label kolom.
#disertai perintah min artinya kolom yang paling kecil

[ 5  9 13]


In [123]:
o = np.max(k)
print(o)
#menampilkan nilai maksimum dari matriks k

16


In [124]:
p = np.max(k,axis=0)
print(p)
#axis=0 digunakan untuk menerapkan metode di setiap kolom, atau ke label baris (indeks), 
#disertai perintah max artinya baris yang paling besar

[13 14 15 16]


In [125]:
q = np.max(k,axis=1)
print(q)
#axis=1 digunakan untuk menerapkan metode di setiap baris, atau ke label kolom.
#disertai perintah max artinya kolom yang paling besar

[ 8 12 16]


In [126]:
r = np.sum(k)
print(r)
#menjumlahkan anggota variabel k

126


In [127]:
s = np.sum(k,axis=0)
print(s)
#axis=0 digunakan untuk menerapkan metode di setiap kolom, atau ke label baris (indeks), 
#disertai perintah sum artinya jumlahkan semua anggota pada tiap kolom

[27 30 33 36]


In [128]:
s = np.sum(k,axis=1)
print(s)
#axis=1 digunakan untuk menerapkan metode di setiap baris, atau ke label kolom.
#disertai perintah sum artinya jumlahkan semua anggota pada tiap baris

[26 42 58]
